-- ============================================================
-- SIP WARGA RT — Skema Supabase untuk halaman "Kelola Kartu Keluarga"
-- Jalankan seluruh isi file ini di: Supabase Dashboard > SQL Editor > New query > Run
-- ============================================================

create extension if not exists "pgcrypto";
create extension if not exists pg_trgm;

-- ------------------------------------------------------------
-- 1. TABEL: kartu_keluarga (master data KK)
-- ------------------------------------------------------------
create table if not exists public.kartu_keluarga (
  id                   bigint generated by default as identity primary key,
  no_kk                varchar(16)  not null unique
                       check (no_kk ~ '^[0-9]{16}$'),
  nama_kepala_keluarga text         not null,
  nik_kepala_keluarga  varchar(16)
                       check (nik_kepala_keluarga is null or nik_kepala_keluarga ~ '^[0-9]{16}$'),
  alamat               text         not null,
  blok                 varchar(10)  not null default 'A'
                       check (blok in ('A','B','C')),
  status_hunian        varchar(20)  not null default 'Tetap'
                       check (status_hunian in ('Tetap','Kontrak','Kos','Pindah')),
  no_hp                varchar(20),
  -- soft delete (FR-05): arsip, bukan hapus permanen
  is_arsip             boolean      not null default false,
  alasan_arsip         text,
  catatan_arsip        text,
  arsip_pada           timestamptz,
  -- audit (FR-18)
  dibuat_oleh          text,
  diperbarui_oleh      text,
  created_at           timestamptz  not null default now(),
  updated_at           timestamptz  not null default now()
);

-- ------------------------------------------------------------
-- 2. TABEL: anggota_keluarga (warga per anggota KK)
-- ------------------------------------------------------------
create table if not exists public.anggota_keluarga (
  id                   bigint generated by default as identity primary key,
  kartu_keluarga_id    bigint       not null
                       references public.kartu_keluarga (id) on delete cascade,
  nik                  varchar(16)  not null unique
                       check (nik ~ '^[0-9]{16}$'),
  nama                 text         not null,
  hubungan_keluarga    varchar(20)  not null default 'Anak'
                       check (hubungan_keluarga in
                         ('Kepala Keluarga','Istri','Suami','Anak','Orang Tua','Menantu','Cucu','Famili Lain')),
  jenis_kelamin        char(1)      not null
                       check (jenis_kelamin in ('L','P')),
  tanggal_lahir        date,
  pekerjaan            text,
  status_kependudukan  varchar(20)  not null default 'Tetap'
                       check (status_kependudukan in ('Tetap','Kontrak','Kos','Pindah')),
  is_arsip             boolean      not null default false,
  created_at           timestamptz  not null default now(),
  updated_at           timestamptz  not null default now()
);

-- mencegah dua "Kepala Keluarga" dalam satu KK (partial unique index)
drop index if exists public.uniq_kk_kepala_keluarga;
create unique index uniq_kk_kepala_keluarga
  on public.anggota_keluarga (kartu_keluarga_id)
  where hubungan_keluarga = 'Kepala Keluarga';

-- ------------------------------------------------------------
-- 3. INDEX untuk pencarian cepat
-- ------------------------------------------------------------
create index if not exists idx_kk_no_kk        on public.kartu_keluarga (no_kk);
create index if not exists idx_kk_kepala       on public.kartu_keluarga using gin (nama_kepala_keluarga gin_trgm_ops);
create index if not exists idx_kk_status_arsip on public.kartu_keluarga (status_hunian, is_arsip);
create index if not exists idx_anggota_kk      on public.anggota_keluarga (kartu_keluarga_id);
create index if not exists idx_anggota_nama    on public.anggota_keluarga using gin (nama gin_trgm_ops);

-- ------------------------------------------------------------
-- 4. TRIGGER updated_at otomatis
-- ------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_kk_updated_at on public.kartu_keluarga;
create trigger trg_kk_updated_at
  before update on public.kartu_keluarga
  for each row execute function public.set_updated_at();

drop trigger if exists trg_anggota_updated_at on public.anggota_keluarga;
create trigger trg_anggota_updated_at
  before update on public.anggota_keluarga
  for each row execute function public.set_updated_at();

-- ------------------------------------------------------------
-- 5. VIEW: v_kelola_kk (struktur seperti KK_LIST di frontend)
--    dipakai halaman KelolaKK: noKK, kepala, alamat, blok, status,
--    anggotaCount, genderKepala, updatedBy, updatedAt, isArsip
-- ------------------------------------------------------------
create or replace view public.v_kelola_kk as
select
  k.id,
  k.no_kk                                    as "noKK",
  k.nama_kepala_keluarga                     as "kepala",
  k.nik_kepala_keluarga                      as "nikKepala",
  k.alamat,
  k.blok,
  k.status_hunian                            as "status",
  k.no_hp                                    as "noHp",
  k.is_arsip                                 as "isArsip",
  k.alasan_arsip                             as "alasanArsip",
  k.catatan_arsip                            as "catatanArsip",
  (select count(*)::int
     from public.anggota_keluarga g
    where g.kartu_keluarga_id = k.id
      and g.is_arsip = false)                as "anggotaCount",
  (select g.jenis_kelamin
     from public.anggota_keluarga g
    where g.kartu_keluarga_id = k.id
      and g.nik = k.nik_kepala_keluarga
    limit 1)                                 as "genderKepala",
  k.diperbarui_oleh                          as "updatedBy",
  k.updated_at                               as "updatedAt",
  k.created_at
from public.kartu_keluarga k;

-- ------------------------------------------------------------
-- 6. ROW LEVEL SECURITY (Supabase)
--    - Aplikasi belum punya login, jadi semua operasi diizinkan
--      untuk anon & authenticated agar CRUD dari frontend jalan.
--    - SETELAH login diaktifkan, GANTI `true` pada policy
--      insert/update/delete dengan: auth.role() = 'authenticated'
--      lalu jalankan ulang script ini.
-- ------------------------------------------------------------
alter table public.kartu_keluarga enable row level security;
alter table public.anggota_keluarga enable row level security;

drop policy if exists kk_select on public.kartu_keluarga;
create policy kk_select on public.kartu_keluarga
  for select using (true);

drop policy if exists kk_insert on public.kartu_keluarga;
create policy kk_insert on public.kartu_keluarga
  for insert with check (true);

drop policy if exists kk_update on public.kartu_keluarga;
create policy kk_update on public.kartu_keluarga
  for update using (true) with check (true);

drop policy if exists kk_delete on public.kartu_keluarga;
create policy kk_delete on public.kartu_keluarga
  for delete using (true);

drop policy if exists anggota_select on public.anggota_keluarga;
create policy anggota_select on public.anggota_keluarga
  for select using (true);

drop policy if exists anggota_insert on public.anggota_keluarga;
create policy anggota_insert on public.anggota_keluarga
  for insert with check (true);

drop policy if exists anggota_update on public.anggota_keluarga;
create policy anggota_update on public.anggota_keluarga
  for update using (true) with check (true);

drop policy if exists anggota_delete on public.anggota_keluarga;
create policy anggota_delete on public.anggota_keluarga
  for delete using (true);

-- ------------------------------------------------------------
-- 7. SEED DATA (sama dengan src/data/mock.js -> KK_LIST)
-- ------------------------------------------------------------
insert into public.kartu_keluarga
  (no_kk, nama_kepala_keluarga, nik_kepala_keluarga, alamat, blok, status_hunian,
   dibuat_oleh, diperbarui_oleh, updated_at)
values
  ('3275012300040001','Bambang Sutrisno','3275011405780001','Jl. Mawar No. 12, Blok A1','A','Tetap',
   'Sekretaris RT (Ibu Nurhayati)','Sekretaris RT (Ibu Nurhayati)','2026-10-07 14:20:00+07'),
  ('3275010903020005','Agus Setiawan','3275010408790008','Jl. Mawar No. 14, Blok A1','A','Kontrak',
   'Sekretaris RT (Ibu Nurhayati)','Sekretaris RT (Ibu Nurhayati)','2026-10-06 10:05:00+07'),
  ('3275011808110002','Hendra Pratama','3275012512920003','Jl. Melati Indah No. 04, Blok B2','B','Kos',
   'Ketua RT (Bpk. Haryono)','Ketua RT (Bpk. Haryono)','2026-10-05 16:40:00+07'),
  ('3275011101990009','Rina Wulandari','3275016203850004','Jl. Mawar No. 08, Blok A1','A','Tetap',
   'Sekretaris RT (Ibu Nurhayati)','Sekretaris RT (Ibu Nurhayati)','2026-10-04 09:12:00+07'),
  ('3275010204120011','Dedi Yulianto','3275010907840002','Eks Jl. Melati No. 21 (Pindah ke Bandung)','B','Pindah',
   'Ketua RT (Bpk. Haryono)','Ketua RT (Bpk. Haryono)','2026-10-01 11:00:00+07'),
  ('3275011507150007','Sutrisno Hadi','3275011007750015','Jl. Anggrek Indah No. 02, Blok C1','C','Tetap',
   'Sekretaris RT (Ibu Nurhayati)','Sekretaris RT (Ibu Nurhayati)','2026-09-28 13:30:00+07')
on conflict (no_kk) do nothing;

-- Anggota keluarga; tanggal_lahir diturunkan dari umur pada mock agar tampil "<umur> th"
insert into public.anggota_keluarga
  (kartu_keluarga_id, nik, nama, hubungan_keluarga, jenis_kelamin, tanggal_lahir, pekerjaan, status_kependudukan)
select k.id, v.nik, v.nama, v.hub, v.jk,
       (current_date - make_interval(years => v.umur))::date,
       v.kerja, k.status_hunian
from (values
  ('3275012300040001','3275011405780001','Bambang Sutrisno','Kepala Keluarga','L',48,'Wiraswasta'),
  ('3275012300040001','3275015208800002','Siti Rahmawati','Istri','P',44,'Guru SD'),
  ('3275012300040001','3275011204050003','Dimas Rizky','Anak','L',19,'Mahasiswa'),
  ('3275012300040001','3275016509120004','Annisa Putri','Anak','P',12,'Pelajar SMP'),
  ('3275010903020005','3275010408790008','Agus Setiawan','Kepala Keluarga','L',45,'Karyawan Swasta'),
  ('3275010903020005','3275015509810009','Dewi Lestari','Istri','P',42,'Ibu Rumah Tangga'),
  ('3275010903020005','3275011008080010','Fajar Setiawan','Anak','L',16,'Pelajar SMA'),
  ('3275011808110002','3275012512920003','Hendra Pratama','Kepala Keluarga','L',33,'Ojek Online'),
  ('3275011101990009','3275016203850004','Rina Wulandari','Kepala Keluarga','P',41,'Pedagang'),
  ('3275011101990009','3275016809100012','Salsa Nabila','Anak','P',15,'Pelajar SMP'),
  ('3275011507150007','3275011007750015','Sutrisno Hadi','Kepala Keluarga','L',51,'PNS'),
  ('3275011507150007','3275014802780016','Sri Mulyani','Istri','P',48,'Bidan'),
  ('3275011507150007','3275010502010017','Bagas Hadi','Anak','L',22,'Karyawan'),
  ('3275011507150007','3275015905060018','Intan Hadi','Anak','P',18,'Mahasiswi'),
  ('3275011507150007','3275017012150019','Kirana Hadi','Anak','P',9,'Pelajar SD'),
  ('3275010204120011','3275010907840002','Dedi Yulianto','Kepala Keluarga','L',42,'Wiraswasta')
) as v(no_kk, nik, nama, hub, jk, umur, kerja)
join public.kartu_keluarga k on k.no_kk = v.no_kk
on conflict (nik) do nothing;

-- Tandai KK Dedi Yulianto sebagai diarsipkan (soft delete)
update public.kartu_keluarga
set is_arsip = true,
    alasan_arsip = 'Pindah domisili keluar RT',
    catatan_arsip = 'Pindah ke Bandung, Kel. Dago per 01 Okt 2026',
    arsip_pada = '2026-10-01 11:00:00+07'
where no_kk = '3275010204120011';

update public.anggota_keluarga g
set is_arsip = true, status_kependudukan = 'Pindah'
from public.kartu_keluarga k
where g.kartu_keluarga_id = k.id and k.no_kk = '3275010204120011';

-- ------------------------------------------------------------
-- 8. CONTOH QUERY UNTUK FRONTEND (Supabase JS)
--
--   // Daftar KK (tanpa arsip)
--   const { data } = await supabase
--     .from('v_kelola_kk')
--     .select('*')
--     .eq('isArsip', false)
--     .order('updatedAt', { ascending: false })
--
--   // Cari kepala keluarga / no KK
--   const { data } = await supabase
--     .from('v_kelola_kk')
--     .select('*')
--     .or(`kepala.ilike.%${q}%,noKK.ilike.%${q}%`)
--
--   // Anggota 1 KK
--   const { data } = await supabase
--     .from('anggota_keluarga')
--     .select('*')
--     .eq('kartu_keluarga_id', kkId)
--     .eq('is_arsip', false)
--
--   // Soft delete (arsip) FR-05
--   await supabase.from('kartu_keluarga').update({
--     is_arsip: true,
--     status_hunian: 'Pindah',
--     alasan_arsip,
--     catatan_arsip,
--     arsip_pada: new Date().toISOString(),
--   }).eq('id', kkId)
-- ------------------------------------------------------------